# Generated by Django 5.1.4 on 2024-12-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='martprices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costomername', models.CharField(max_length=100)),
                ('product_1', models.CharField(max_length=100)),
                ('product_2', models.CharField(max_length=100)),
                ('product_3', models.CharField(max_length=100)),
                ('product_4', models.CharField(max_length=100)),
                ('product_5', models.CharField(max_length=100)),
                ('product_6', models.CharField(max_length=100)),
                ('product_7', models.CharField(max_length=100)),
            ],
        ),
    ]
