# Generated by Django 5.1.4 on 2024-12-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='martprices',
            name='product_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='martprices',
            name='product_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='martprices',
            name='product_3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='martprices',
            name='product_4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='martprices',
            name='product_5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='martprices',
            name='product_6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='martprices',
            name='product_7',
            field=models.IntegerField(),
        ),
    ]
